/**
 * Bridge between the hand-written solution content and the generated
 * catalogue.
 *
 * The two are maintained independently — `products.json` is regenerated by
 * `npm run data`, `solutions.ts` is written by hand — so every join between
 * them is defensive. A `relatedCategorySlugs` entry that no longer resolves
 * is reported once at build time and skipped, because a renamed category
 * should degrade one products grid, not fail the build.
 */
import { solutionContent, type SolutionContent } from "@/data/solutions";
import { SOLUTION_NAV, solutionNameBySlug } from "@/data/solution-nav";
import {
  getCategory,
  getCategoryTrail,
  getProductsInCategory,
  getCategoryHeroImage,
  type Category,
  type Product,
  type ProductImage,
} from "@/lib/catalog";

/** Content plus the display name and menu blurb from the nav module. */
export type Solution = SolutionContent & {
  name: string;
  navBlurb: string;
};

/**
 * Joined once per process, in `SOLUTION_NAV` order — so the menu, the hub
 * grid and the horizontal showcase all present the seven in the same
 * sequence no matter which one they read from.
 */
export const solutions: Solution[] = SOLUTION_NAV.map((nav) => {
  const content = solutionContent.find((c) => c.slug === nav.slug);

  if (!content) {
    // Unreachable while `SolutionContent["slug"]` is typed as SolutionSlug,
    // but a missing entry would otherwise render a nameless empty page.
    throw new Error(
      `[solutions] "${nav.slug}" is listed in SOLUTION_NAV but has no entry ` +
        `in src/data/solutions.ts.`,
    );
  }

  return { ...content, name: nav.name, navBlurb: nav.navBlurb };
});

const solutionBySlug = new Map(solutions.map((s) => [s.slug, s]));

export function getSolution(slug: string): Solution | undefined {
  return solutionBySlug.get(slug as Solution["slug"]);
}

export { SOLUTION_NAV, solutionNameBySlug };

/* ------------------------------------------------------------------ *
 * Category resolution
 * ------------------------------------------------------------------ */

/** Slugs already warned about, so a shared bad slug logs once, not per page. */
const warned = new Set<string>();

/**
 * The categories a solution points at, in declared order, skipping any that
 * no longer exist in the taxonomy.
 */
export function getSolutionCategories(solution: Solution): Category[] {
  const out: Category[] = [];

  for (const slug of solution.relatedCategorySlugs) {
    const category = getCategory(slug);

    if (!category) {
      if (!warned.has(slug)) {
        warned.add(slug);
        console.warn(
          `[solutions] "${solution.slug}" references category "${slug}", ` +
            `which is not in categories.json — skipping it. Update ` +
            `relatedCategorySlugs in src/data/solutions.ts.`,
        );
      }
      continue;
    }

    out.push(category);
  }

  return out;
}

/**
 * Products across a solution's categories, de-duplicated (the categories
 * overlap by design) and preferring items that have imagery, since these land
 * in a visual grid.
 */
export function getSolutionProducts(solution: Solution, limit = 8): Product[] {
  const seen = new Set<number>();
  const pool: Product[] = [];

  for (const category of getSolutionCategories(solution)) {
    for (const product of getProductsInCategory(category)) {
      if (seen.has(product.id)) continue;
      seen.add(product.id);
      pool.push(product);
    }
  }

  return pool
    .sort(
      (a, b) =>
        Number(b.images.length > 0) - Number(a.images.length > 0) ||
        b.standards.length - a.standards.length,
    )
    .slice(0, limit);
}

/** Total catalogue depth behind a solution — used for the "view all" count. */
export function countSolutionProducts(solution: Solution): number {
  const seen = new Set<number>();
  for (const category of getSolutionCategories(solution)) {
    for (const product of getProductsInCategory(category)) seen.add(product.id);
  }
  return seen.size;
}

/**
 * The catalogue page a solution's "View all" should land on: its first
 * resolvable category, walked up to a depth that actually has a route.
 *
 * Only depth 0 and depth 1 categories are generated as pages, so a solution
 * pointing at a depth-3 slug (`aluminized-para-aramid`, say) still needs a
 * link that resolves.
 */
export function getSolutionCategoryHref(solution: Solution): string | null {
  const [first] = getSolutionCategories(solution);
  if (!first) return null;

  const trail = getCategoryTrail(first.slug);
  const main = trail[0];
  if (!main) return null;

  const sub = trail[1];
  return sub && !sub.synthetic
    ? `/products/${main.slug}/${sub.slug}`
    : `/products/${main.slug}`;
}

/** Hero image for a solution card — the first category that has one. */
export function getSolutionImage(solution: Solution): ProductImage | null {
  for (const category of getSolutionCategories(solution)) {
    const image = getCategoryHeroImage(category);
    if (image) return image;
  }
  return null;
}
