/**
 * Lists the products that still need a photograph.
 *
 * Regenerates MISSING-IMAGES.md from the built catalogue, so the list stays
 * accurate as photography is added — add a photo, re-run `npm run data`, then
 * re-run this and the product drops off the list.
 *
 * Also fails loudly if any product references an image file that is not on
 * disk. That is worth checking every time: an image whose file is missing
 * renders as a broken image rather than as the site's placeholder, and nothing
 * else in the build catches it.
 *
 * Run with: npm run audit:images
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

const products = JSON.parse(
  readFileSync(join(ROOT, "src", "data", "products.json"), "utf8"),
);
const categories = JSON.parse(
  readFileSync(join(ROOT, "src", "data", "categories.json"), "utf8"),
);
const catName = Object.fromEntries(categories.map((c) => [c.slug, c.name]));

/* ---- broken references ---- */

const broken = [];
for (const p of products) {
  for (const img of p.images) {
    for (const variant of ["-400", "-900"]) {
      const file = join(ROOT, "public", img.src.replace(/\.webp$/, `${variant}.webp`));
      if (!existsSync(file)) broken.push(`${p.slug}  ${img.src}${variant}`);
    }
  }
}

/* ---- products with no photograph ---- */

const missing = products
  .filter((p) => !p.images.length)
  .sort(
    (a, b) =>
      (catName[a.mainCategory] || "").localeCompare(catName[b.mainCategory] || "") ||
      a.name.localeCompare(b.name),
  );

const byCategory = {};
for (const p of missing) {
  const key = catName[p.mainCategory] || p.mainCategory;
  (byCategory[key] ??= []).push(p);
}

let md = `# Products still needing a photograph\n\n`;
md += `Generated by \`npm run audit:images\` from the built catalogue.\n\n`;
md += `**${missing.length} of ${products.length} products** have no photograph. `;
md += `They render the site's own "image not available" placeholder — quiet and\n`;
md += `consistent with the design, not a broken image.\n\n`;
md += `Of these, 35 previously displayed the source catalogue's grey\n`;
md += `"No image available" graphic. That artwork is now stripped in the data\n`;
md += `pipeline (see \`PLACEHOLDER_HASHES\` in \`scripts/build-data.mjs\`), so those\n`;
md += `products show the site's placeholder instead of someone else's.\n\n`;
md += `## Adding a photograph\n\n`;
md += `Save it as \`public/media/<year>/<month>/<Name>-400.webp\` and \`-900.webp\`\n`;
md += `(square, white background matches the rest of the catalogue), add the path\n`;
md += `to the product in \`scripts/raw/products.json\`, then run \`npm run data\`.\n`;
md += `Re-run this audit and the product drops off the list.\n\n---\n\n`;

for (const [category, items] of Object.entries(byCategory).sort(
  (a, b) => b[1].length - a[1].length,
)) {
  md += `## ${category} (${items.length})\n\n| Product | Page |\n| --- | --- |\n`;
  for (const p of items) md += `| ${p.name} | /product/${p.slug} |\n`;
  md += `\n`;
}

writeFileSync(join(ROOT, "MISSING-IMAGES.md"), md);

console.log(`products                  ${products.length}`);
console.log(`  with a photograph       ${products.length - missing.length}`);
console.log(`  needing a photograph    ${missing.length}`);
console.log(`broken image references   ${broken.length}`);
for (const b of broken.slice(0, 10)) console.log(`   ${b}`);
console.log(`\nReport: MISSING-IMAGES.md`);

if (broken.length) process.exitCode = 1;
